src/Entity/Website.php
<?php

namespace App\Entity;

use App\Repository\WebsiteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WebsiteRepository::class)
 */
class Website
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $website_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $thumbnail;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWebsiteTitle(): ?string
    {
        return $this->website_title;
    }

    public function setWebsiteTitle(string $website_title): self
    {
        $this->website_title = $website_title;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(string $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }
}

src/Controller/BackController.php
<?php

namespace App\Controller;

use App\Entity\Website;
use App\Form\WebsiteType;
use App\Repository\WebsiteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BackController extends AbstractController
{
    /**
     * @Route("/backOffice", name="backOffice")
     */
    public function backOffice(Request $request, EntityManagerInterface $manager, WebsiteRepository $repository)
    {

        $form = $this->createForm(WebsiteType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()):

            $website = $form->getData();
            $picture = $form->get("picture")->getData();
            $thumbnail = $form->get("thumbnail")->getData();

            if ($picture && $thumbnail):

                $namePicture = date("YmdHis") . uniqid() . $picture->getClientOriginalName();
                $nameThumbnail = date("YmdHis") . uniqid() . $picture->getClientOriginalName();

                $picture->move(
                    $this->getParameter("upload_directory"),
                    $namePicture
                );

                $thumbnail->move(
                    $this->getParameter("upload_directory"),
                    $nameThumbnail
                );

                $website->setPicture($namePicture);
                $website->setThumbnail($nameThumbnail);

            endif;

            $manager->persist($website);
            $manager->flush();

            $this->addFlash('success', 'Le site a bien été ajouté');

            return $this->redirectToRoute("backOffice");

        elseif ($form->isSubmitted() && !$form->isValid()):

            $this->addFlash("error", "Un problème est survenue lors de l'ajout");

        endif;

        return $this->render("back/backOffice.html.twig", [
            "title" => "Ajouter un site",
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/websiteManager", name="websiteManager")
     */
    public function websiteManager(WebsiteRepository $repository)
    {
        $websites = $repository->findAll();

        return $this->render("back/websiteManager.html.twig", [
            "title" => "Liste des sites",
            "websites" => $websites
        ]);
    }

    /**
     * @Route("/editWebsite/{id}", name="editWebsite")
     */
    public function editWebsite(Request $request, WebsiteRepository $repository, EntityManagerInterface $manager, $id = null)
    {

        $websites = $repository->find($id);

        $form = $this->createForm(WebsiteType::class, $websites);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()):

            $website = $form->getData();
            $picture = $form->get("picture")->getData();
            $thumbnail = $form->get("thumbnail")->getData();

            if ($picture && $thumbnail):

                $namePicture = date("YmdHis") . uniqid() . $picture->getClientOriginalName();
                $nameThumbnail = date("YmdHis") . uniqid() . $picture->getClientOriginalName();

                $picture->move(
                    $this->getParameter("upload_directory"),
                    $namePicture
                );

                $thumbnail->move(
                    $this->getParameter("upload_directory"),
                    $nameThumbnail
                );

                $website->setPicture($namePicture);
                $website->setThumbnail($nameThumbnail);

            endif;

            $manager->persist($website);
            $manager->flush();

            $this->addFlash('success', 'Le site a bien été ajouté');

            return $this->redirectToRoute("backOffice");

        elseif ($form->isSubmitted() && !$form->isValid()):

            $this->addFlash("error", "Un problème est survenue lors de l'ajout");

        endif;

        return $this->render("back/editWebsite.html.twig", [

            "title" => "Editer un site",
            "form" => $form->createView()
        ]);
    }
}

templates/back/backOffice.html.twig
{% extends 'baseBack.html.twig' %}

{% block body %}

    <section id="form-add-website" class="text-dark mx-auto" style="width: 80%">
        {{ form_start(form) }}

        <div class="website-title-input">
            <div class="mt-4 mb-2">Titre du site</div>
            {{ form_row(form.website_title) }}
        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Description</div>
            {{ form_row(form.description) }}
        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Adresse du site</div>
            {{ form_row(form.url) }}
        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Image du site</div>
            {{ form_row(form.picture, { 'attr':{"onChange": "loadFile(event)"} }  ) }}
        </div>
        <div class="col-md-12 text-center mb-3">

            <img id="image" style='width:400px'>

        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Miniature</div>
            {{ form_row(form.thumbnail, { 'attr':{"onChange": "loadFile2(event)"} }  ) }}
        </div>
        <div class="col-md-12 text-center mb-5">

            <img id="image2" style='width:400px'>

        </div>

        <div class="btn-submit mb-5">
            {{ form_row(form.Ajouter) }}
        </div>

        {{ form_end(form) }}
    </section>

    <script>
        var loadFile = function (event) {
            var image = document.getElementById('image');
            image.src = URL.createObjectURL(event.target.files[0]);
        };

        var loadFile2 = function (event) {
            var image2 = document.getElementById('image2');
            image2.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>

{% endblock %}

{% block title %}

{% endblock %}

templates/back/editWebsite.html.twig
{% extends 'baseBack.html.twig' %}

{% block body %}

    <section id="form-add-website" class="text-dark mx-auto" style="width: 80%">
        {{ form_start(form) }}

        <div class="website-title-input">
            <div class="mt-4 mb-2">Titre du site</div>
            {{ form_row(form.website_title) }}
        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Description</div>
            {{ form_row(form.description) }}
        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Adresse du site</div>
            {{ form_row(form.url) }}
        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Image du site</div>
            {{ form_row(form.picture, { 'attr':{"onChange": "loadFile(event)"} }  ) }}
        </div>
        <div class="col-md-12 text-center mb-3">

            <img id="image" style='width:400px'>

        </div>

        <div class="website-title-input">
            <div class="mt-4 mb-2">Miniature</div>
            {{ form_row(form.thumbnail, { 'attr':{"onChange": "loadFile2(event)"} }  ) }}
        </div>
        <div class="col-md-12 text-center mb-5">

            <img id="image2" style='width:400px'>

        </div>

        <div class="btn-submit mb-5">
            {{ form_row(form.Ajouter) }}
        </div>

        {{ form_end(form) }}
    </section>

    <script>
        var loadFile = function (event) {
            var image = document.getElementById('image');
            image.src = URL.createObjectURL(event.target.files[0]);
        };

        var loadFile2 = function (event) {
            var image2 = document.getElementById('image2');
            image2.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>

{% endblock %}

{% block title %}

{% endblock %}

templates/back/websiteManager.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}

    <section id="websites-table">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>

            {% for website in websites %}
                
            <tr>
                <td class="fs-5">{{ website.websiteTitle }}</td>
                <td>
                    <a href="{{ path('editWebsite', {'id': website.id }) }}" class="btn btn-primary">Modifier</a>
                    <a href="" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>

            {% endfor %}

            </tbody>
        </table>
    </section>

{% endblock %}